name: azure-static-website
run-name: Ferouze
on:
  push:
    branches:
      - main
jobs:
  push-site-toazure:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Get IP address
        run: |
          $ipget = $(curl 'https://api.ipify.org')
          echo $ipget
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_NEW }}'
      
      - name: Deploy to Azure Static Website
        run: |
          az storage blob upload-batch --overwrite --account-name 10wcosa --connection-string '${{ secrets.AZURE_STORAGE_CONNECTIONSTRING}}' --destination '$web' --source ./week1/site/ --pattern "*.html"
    
   
