name: azure-static-website
run-name: Ferouze
on:
  push:
    branches:
      - main
jobs:
  push-site-toazure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS_NEW }}'
  
    - name: Deploy to Azure Static Website
      run: |
        az storage blob upload-batch --destination '$web' --source ./week1/site/ --pattern "*.html"
    
    
#
