name: azure-static-website
run-name: Ferouze
on:
  push:
    branches:
      - main
    paths:
      - 'week1/site/**'
jobs:
  push-site-toazure:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: echo variables
        run: |
          echo cred '${{ secrets.AZURE_CREDENTIALS_13MAY}}'
          echo connection string '${{ secrets.AZURE_STORAGE_CONNECTIONSTRING}}'
          echo cdn name '${{secrets.AZURE_CDN_NAME}}'
          echo cdn resource group '${{ secrets.AZURE_CDN_RESOURCEGROUP}}'
          echo cdn profile name '${{ secrets.AZURE_CDN_PROFILENAME}}'
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_13MAY}}'
          
      - name: Add the IP address to azure storage exclusion
        run: |
          ip_address=$(curl https://api.ipify.org -s)
          echo The IP address of the runner is $ip_address
          az storage account network-rule add --account-name 10wcosa --ip-address $ip_address
          sleep 200
      - name: Deploy to Azure Static Website
        run: |
          az storage blob upload-batch --overwrite --account-name 10wcosa --connection-string '${{ secrets.AZURE_STORAGE_CONNECTIONSTRING}}' --destination '$web' --source ./week1/site/ --pattern "*.html"
      - name: Purge CDN to clear all the cache
        run: | 
          az cdn endpoint purge --resource-group '${{ secrets.AZURE_CDN_RESOURCEGROUP}}' --name '${{secrets.AZURE_CDN_NAME}}' --profile-name '${{ secrets.AZURE_CDN_PROFILENAME}}' --content-paths '/*'
          sleep 60
      - name: Remove excluded IP from storage
        run: |
          ip_address=$(curl https://api.ipify.org -s)
          az storage account network-rule remove --account-name 10wcosa --ip-address $ip_address
        
   
