name: azure-static-website
run-name: Ferouze
on:
  push:
    branches:
      - main
jobs:
  push-site-toazure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Get IP address
      id: ip
      run: |
       apt install -y jq
       ipjson=$(curl 'https://api.ipify.org?format=json' -s)
       ipaddr=$(echo $ipjson | jq .ip -r)
       echo $ipaddr
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS_NEW }}'
  
    - name: Deploy to Azure Static Website
      run: |
        az storage blob upload-batch --overwrite --account-name 10wcosa --connection-string '${{ secrets.AZURE_STORAGE_CONNECTIONSTRING}}' --destination '$web' --source ./week1/site/ --pattern "*.html"
    
    

