name: azure-static-website
run-name: Ferouze
on:
  push:
    branches:
      - main
jobs:
  push-site-toazure:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Get IP address
        run: |
          ip_address=$(curl https://api.ipify.org -s)
          echo $ip_address
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_NEW }}'
          
      - name: Add the IP address to azure storage exclusion
        run: |
          az storage account network-rule add --account-name 10wcosa --ip-address $ip_address
      
      - name: Deploy to Azure Static Website
        run: |
          az storage blob upload-batch --overwrite --account-name 10wcosa --connection-string '${{ secrets.AZURE_STORAGE_CONNECTIONSTRING}}' --destination '$web' --source ./week1/site/ --pattern "*.html"
    
   
